# -*- coding: utf-8 -*-
import json
R = [
("ETO-RD-DP 00019/2026","5710094091","QUEIMADO","MANTER","alta",
 "Trafo e para-raios queimados por descarga, troca fisica comprovada (serie 453193->590883) e interrupcao no proprio trafo na janela.",
 "Constatado trafo 5710094091 de 75kVA na 34.5kV e para-raios queimados / subcausa QUEIMADO POR DESCARGA ATMOSFERICA", False),
("ETO-RD-AR 00032/2026","5700569016","QUEIMADO","MANTER","alta",
 "Queima do proprio trafo (5kVA) com troca comprovada por serie/tombamento e ocorrencia casada; o aumento para 15kVA foi consequencia, nao o motivo.",
 "TRAFO QUEIMADO (COLOCAR UM MAIOR) POTENCIA 5KVA / Nº DE SERIE: 460298 -> 431980", False),
("ETO-RD-AG 00047/2026","5700989039","AVARIADO","MANTER","alta",
 "Vazamento de oleo no proprio transformador, confirmado em campo e pela subcausa da Critica, com troca fisica registrada.",
 "SUBSTITUIR TRAFO QUEIMADO (VASAMENTO DE OLEO) / subcausa VAZAMENTO DE OLEO / TANQUE DETERIORADO", False),
("ETO-RD-GU 00077/2026","5710788037","QUEIMADO","MANTER","alta",
 "Trafo e para-raio queimados, ocorrencia casada pelo trafo com subcausa de queima por descarga e troca executada.",
 "SS DE TRAFO QUEIMADO NA RDR DE ALIANCA, TRAFO DE 10KVA / QUEIMADO POR DESCARGA ATMOSFERICA", False),
("ENC-RD-PS 00103/2026","5301988007","AVARIADO","MANTER","media",
 "Falha do proprio equipamento (vazamento de oleo e perda de fase na secundaria) com troca comprovada na OS; a Critica so ficou 2,1h fora da janela.",
 "Segue SS de TR 5301988007 25KVA/19.9KV com vazamento de oleo. Esta saindo somente uma fase na secundaria", False),
("ETO-RD-AR 00168/2026","5700481040","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS aberta e executada como melhoria de posto de transformacao (relatorio e book), sem evento de falha do equipamento na origem.",
 "MELHORIA EM POSTO DE TRANSFORMACAO PREENCHER RELATORIO E BOOK PARA MELHORIAS EM POSTO DE TRANSFORMACAO", False),
("ETO-RD-AR 00188/2026","5739688157","QUEIMADO","MANTER","media",
 "Queima do trafo e do para-raio com troca comprovada; o site excluiu apenas por nao casar janela (571h), o que nao e causa alheia ao equipamento.",
 "TRAFO QUEIMADO 5739688157 pararaio queimado acesso caminhonete / PROVAVEL MOTIVO: DESCARGA ATMOSFERICA", True),
("ETO-RD-GR 00165/2026","5700405154","AVARIADO","MANTER","alta",
 "OS declara troca de trafo avariado por vazamento de oleo, com serie/tombamento nos dois lados e ocorrencia casada.",
 "TROCA DE TRAFO AVARIADO 5700405154 / EQUIPAMENTO APRESENTA VAZAMENTO DE OLEO=Sim", False),
("ETO-RD-AR 00219/2026","5710365060","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS de melhoria em posto de transformacao, sem defeito do equipamento declarado e com a ocorrencia fora da janela.",
 "MELHORIA EM POSTO DE TRANSFORMACAO PREENCHER RELATORIO E BOOK / tipo_ss MELHORIA POSTO DE TRANSFORMACAO", False),
("DOLP-RD-PA 00209/2026","5700767026","QUEIMADO","MANTER","alta",
 "Trafo queimado por sobrecarga com interrupcao casada no proprio trafo e troca comprovada por serie.",
 "5700767026 QUEIMADO POT. 15KVA / subcausa QUEIMADO POR SOBRECARGA", False),
("ETO-RD-AG 00171/2026","5722963124","AVARIADO","MANTER","alta",
 "Vazamento de oleo do proprio trafo, confirmado pela subcausa e pela observacao do executante, com troca fisica registrada.",
 "SUBSTITUICAO DE TRAFO 5722963124 COM VAZAMENTO DE OLEO / VAZAMENTO DE OLEO / TANQUE DETERIORADO", False),
("ETO-RD-AG 00184/2026","5748172045","QUEIMADO","MANTER","alta",
 "Trafo de 45kVA queimado com para-raios ruins, ocorrencia casada pelo trafo e troca comprovada por serie/tombamento.",
 "5748172045 QUEIMADO POT. 45KVA 34,5KV PARA-RAIO BT E MT RUIM / QUEIMADO POR CAUSA NAO IDENTIFICADA", False),
("ETO-RD-AR 00313/2026","5701760004","AVARIADO","MANTER","alta",
 "Trafo vazando oleo, vazamento confirmado no formulario de campo e troca comprovada; falha do proprio equipamento.",
 "trafo 5701760004 vazando oleo / EQUIPAMENTO APRESENTA VAZAMENTO DE OLEO=Sim", False),
("DOLP-RD-PA 00264/2026","5761911122","ABALROAMENTO","EXPURGAR","alta",
 "Dano causado por caminhao que acertou os cabos; causa de rede/terceiro, nao falha do transformador.",
 "SEGUE SS DE TRAFO 5761911122 QUEIMADO NA RDU DE PALMAS. DEVIDO CAMINHAO / Causa cabos entrelacados passou um caminhao", False),
("ETO-RD-GR 00253/2026","5700718113","AVARIADO","MANTER","media",
 "Vazamento de oleo do proprio trafo, com ocorrencia casada e subcausa coincidente; formulario de campo pouco preenchido.",
 "Trafo: 5700718113 vazameto de oleo / subcausa VAZAMENTO DE OLEO / TANQUE DETERIORADO", False),
("ETO-RD-AR 00342/2026","5700963077","MELHORIA DE POSTO","EXPURGAR","alta",
 "Servico aberto e executado como melhoria em posto de transformacao, com correcao de cadastro de potencia; ocorrencia fora da janela.",
 "Realizar melhoria em posto de transformador 5700963077. / ERRO DE CADATRO", False),
("ETO-RD-AG 00214/2026","5700722045","AVARIADO","MANTER","media",
 "OS registra severo vazamento de oleo e tap submerso impedindo regularizacao, ou seja, o proprio equipamento estava avariado.",
 "SUBSTITUICAO DE TRANSFORMADOR SEVERO VAZAMENTO DE OLEO / DEVIDO AO TAP DENTRO DO OLEO, NAO FOI POSSIVEL NORMALIZAR", False),
("ETO-RD-AR 00374/2026","5755876004","MELHORIA DE POSTO","EXPURGAR","media",
 "SS de melhoria de aterramento com troca por trafo de mesma potencia e mesma familia de tombamento; a Critica casada nao e sustentada pelo texto do servico.",
 "REALIZAR MELHORIA DE ATERRAMENTO / RETIRADO 45 KVA CITD 113237 -> INSTALADO 45 KVA CITD 113257", False),
("ETO-RD-GU 00275/2026","5700029003","QUEIMADO","MANTER","alta",
 "Teste a vazio confirmou trafo queimado em campo, com queima de elo e interrupcao casada no proprio trafo.",
 "Feito teste a vazio e confirmado Trafo queimado em campo / Causa: DESCARGA ATMOSFERICA", False),
("ETO-RD-AR 00421/2026","5701278016","MELHORIA DE POSTO","EXPURGAR","media",
 "SS aberta como melhoria de aterramento em posto de transformacao; o texto do servico nao registra falha do equipamento.",
 "REALIZAR MELHORIA DE ATERRAMENTO / tipo_ss MELHORIA POSTO DE TRANSFORMACAO", False),
("ETO-RD-GR 00316/2026","5700958033","QUEIMADO","MANTER","media",
 "SS e OS declaram trafo queimado e a Critica casou pelo trafo com queima por descarga; formulario de campo em branco.",
 "trafo 5700958033 queimado / subcausa QUEIMADO POR DESCARGA ATMOSFERICA", False),
("ETO-RD-DP 00182/2026","5700273116","FURTO","EXPURGAR","alta",
 "SS e OS identicas registram trafo e para-raios furtados, e o campo aponta motivo FURTADO; nao e queima nem avaria.",
 "Constatado trafo 5700273116 de 15kVA na 19.9kV e para-raios furtados. / PROVAVEL MOTIVO DO DEFEITO=FURTADO", False),
("ENC-RD-PS 00352/2026","5701313007","QUEIMADO","MANTER","alta",
 "Trafo queimado com interrupcao casada por descarga e troca fisica comprovada por serie e tombamento.",
 "Trafo queimado / subcausa QUEIMADO POR DESCARGA ATMOSFERICA / Nº DE SERIE 128397 -> 827781", False),
("ETO-RD-AR 00498/2026","5701102022","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS de melhoria de aterramento em posto de transformacao, com ocorrencia 120h fora da janela.",
 "Realizar melhoria de aterramento / TRAFO FORA DA JANELA dist_h=119.9", False),
("ETO-RD-AG 00319/2026","5700284131","QUEIMADO","MANTER","alta",
 "OS de substituicao de trafo queimado, interrupcao casada por descarga atmosferica e troca comprovada.",
 "OS PARA SUBSTITUICAO DE TRAFO QUEIMADO - 5700284131 - trafo queimado", False),
("ENC-RD-PS 00421/2026","5723840122","AVARIADO","MANTER","media",
 "Texto do solicitante atribui a substituicao a vazamento de oleo do proprio trafo e a troca esta comprovada por serie/tombamento.",
 "Causa: Devido vazamento de oleo / Nº DE SERIE 28678 -> 182565", False),
("ETO-RD-AR 00598/2026","5730971019","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS de melhoria no posto de transformacao, com troca por trafo novo de mesma potencia e ocorrencia fora da janela.",
 "Realizar melhoria no trafo 5730971019 / tipo_ss MELHORIA POSTO DE TRANSFORMACAO", False),
("ETO-RD-GR 00400/2026","5700214066","QUEIMADO","MANTER","media",
 "A OS declara troca de trafo queimado com dados completos dos dois equipamentos; a exclusao do site foi por ausencia de interrupcao, nao por causa alheia.",
 "TROCA DE TRAFO QUEIMADO 5700214066 ETO-RD-GR 400/2026 ZONA RURAL - TUPIRATINS", True),
("ETO-RD-AR 00675/2026","5700912077","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS de melhoria de aterramento com correcao de cadastro de potencia; ocorrencia 70h fora da janela.",
 "Realizar melhoria de aterramento no trafo 5700912077 / ERRO DE CADASTRO", False),
("ETO-RD-AR 00697/2026","5700677080","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS de melhoria de aterramento em posto de transformacao, troca por trafo novo de mesma potencia (25kVA).",
 "Melhoria de aterramento 5700677080 / RETIRADO 25 KVA -> INSTALADO 25 KVA", False),
("DG-RD-PO 00356/2026","5762253026","QUEIMADO","MANTER","alta",
 "SS e OS declaram substituicao de trafo queimado de 75kVA, com interrupcao casada no proprio trafo.",
 "medido_ emergencial_ substituicao de trafo queimado rdr ponte alta", False),
("ETO-RD-AR 00798/2026","5701003040","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS explicitamente de melhoria no posto de transformacao; ocorrencia 116h fora da janela.",
 "FAZER MELHORIA NO POSTO DE TRANFORMACAO NO TRAFO 5701003040", False),
("ETO-RD-AR 00818/2026","5710240030","AVARIADO","MANTER","media",
 "Vazamento de oleo no proprio trafo com troca comprovada por serie/tombamento; a exclusao do site foi por ausencia de registro de interrupcao.",
 "Trafo 5710240030 Vazamento de oleo Potencia: 10 KVA / Nº DE SERIE 392515 -> 1123921", True),
("ETO-RD-AR 00888/2026","5701279040","MELHORIA DE POSTO","EXPURGAR","alta",
 "SS de melhoria em posto de transformacao, troca por trafo reformado de mesma potencia e ocorrencia 94h fora da janela.",
 "fazer melhoria no posto de transformacao no trafo 5701279040", False),
("DOLP-RD-PA 00635/2026","5710177010","AVARIADO","MANTER","alta",
 "Causa declarada e vazamento de oleo do proprio trafo, confirmada no campo e pela subcausa da Critica, com troca comprovada.",
 "CHECK LIST TRAFO QUEIMADO - Trafo: 5710177010 - Causa: vazamento de oleo / VAZAMENTO DE OLEO / TANQUE DETERIORADO", False),
("DG-RD-PO 00422/2026","5710036026","AVARIADO","MANTER","alta",
 "Defeito interno do transformador (tap submerso, tensao fora de faixa) com interrupcao casada de causa TRANSFORMADOR e troca comprovada.",
 "trafo 5710036026 com defeito interno e tap submerso tensao muito alta no trafo impossibilitando alteracao", False),
("DG-RD-PO 00433/2026","5710100256","QUEIMADO","MANTER","alta",
 "OS de substituicao de trafo queimado, com para-raio queimado e falha de bucha de BT registrada na Critica.",
 "medido_ emergencial_ substituicao de trafo queimado rdr mateiros / subcausa FALHA BUCHA DE BT", False),
("DG-RD-PO 00436/2026","5721874257","ABALROAMENTO","EXPURGAR","alta",
 "Dois postes quebrados e bucha danificada, com a Critica apontando POSTE DE BT / ABALROADO: dano externo, nao falha do trafo.",
 "02 poste 10/150 quebrado / causa POSTE DE BT subcausa ABALROADO", False),
("DOLP-RD-PA 00713/2026","5364882001","AVARIADO","MANTER","media",
 "A manutencao condenou o proprio transformador (choque/elevacao de tensao) e houve troca fisica registrada; a Critica aponta causa TRANSFORMADOR.",
 "Manutencao foi ao local recuperar malha de aterramento e condenou o TRAFO. Risco a comunidade.", False),
("ENC-RD-PS 00645/2026","5700096013","INCONCLUSIVO","EXPURGAR","baixa",
 "A SS aponta trafo errado (o trocado foi o 5700096012) e nenhum texto descreve queima ou avaria; falta o motivo do defeito para decidir.",
 "POR ERRO DO OPERADOR NA ABERTURA DA SS FOI INFORMADO O TRAFO ERRADO / TRAFO CORRETO 5700096012", False),
("ETO-RD-GU 00775/2026","5700194003","QUEIMADO","MANTER","alta",
 "Transformador de 75kVA declarado queimado na RDU de Gurupi, com interrupcao casada pelo proprio trafo penalizando 68 clientes e troca comprovada.",
 "Transformador 5700194003 queimado , 75KVA - 13.8 , RDU GURUPI JD ELDORADO", False),
]
src = json.load(open('/tmp/claude-0/-home-user/74dc9c64-5026-54ee-a81e-173d2f38a735/scratchpad/lote205/lote_3.json'))
assert len(R) == len(src) == 41
out=[]
for rec, c in zip(R, src):
    ss, trafo, cls, dec, conf, just, ev, div = rec
    assert c['ss'].strip() == ss and c['trafo'] == trafo, (c['ss'], ss)
    out.append({"ss": c['ss'], "trafo": trafo, "classificacao": cls, "decisao": dec,
                "confianca": conf, "justificativa": just, "evidencia": ev[:200],
                "diverge_do_site": div})
p='/tmp/claude-0/-home-user/74dc9c64-5026-54ee-a81e-173d2f38a735/scratchpad/lote205/saida_3.json'
json.dump(out, open(p,'w'), ensure_ascii=False, indent=2)
from collections import Counter
print('total', len(out))
print(Counter(o['classificacao'] for o in out))
print(Counter(o['decisao'] for o in out))
print('diverge', sum(1 for o in out if o['diverge_do_site']), [o['ss'] for o in out if o['diverge_do_site']])
print('baixa', [o['ss'] for o in out if o['confianca']=='baixa'])
print('media', [o['ss'] for o in out if o['confianca']=='media'])
