// Conteúdo do protocolo. Cada seção: {t: título, itens: [...]}
// item: {p: "parágrafo"} | {b: ["bullet", ...]} | {n: ["numerado", ...]} | {tab: {h: [...], r: [[...],...], w: [...]}} | {h3: "subtítulo"} | {q: "destaque"}
module.exports = {
titulo: "Protocolo de leitura de SS, OS e OS Status",
subtitulo: "Comando de trabalho para uma IA categorizar substituições de transformador usando somente essas três bases",
secoes: [
{ t: "Seu papel e o que se espera de você", itens: [
  {p: "Você é um auditor de substituições de transformador de distribuição. Vai receber três bases: a base SS/OS (solicitações de serviço com a ordem de serviço e o formulário de campo), a base de OS Status (situação e datas de cada ordem de serviço) e nada mais. Seu trabalho é ler cada SS como um caso, não como uma linha: conferir todos os campos, cruzar as datas, olhar o histórico do transformador, investigar a causa e só então dar uma categoria."},
  {p: "Para cada SS você entrega uma categoria, a resposta “conta” ou “não conta” no indicador, um grau de confiança, o motivo em uma frase e a evidência citada (nome do campo e trecho do texto). Nunca entregue categoria sem evidência."},
  {q: "O indicador de 1.305 e os universos de 1.582 e 1.510 estão congelados. Você não recalcula nada. Sua leitura corre ao lado do caso e serve para explicar, não para substituir."},
  {b: [
    "Use somente SS/OS e OS Status. Não suponha Crítica, obra, material de almoxarifado nem TMAE. O que depender dessas fontes você marca como NÃO VERIFICÁVEL COM ESTAS FONTES e segue.",
    "Trate os textos como depoimentos: a conclusão da OS é o que a equipe viu no poste; a SS é o que quem abriu o chamado suspeitava. Em conflito, a OS manda.",
    "Falta de registro não é prova de que o transformador estava bom. Quando faltar prova, diga que falta prova; não diga que não houve falha.",
    "Nunca decida por um campo só. Toda categoria precisa de pelo menos dois sinais que combinem (texto + número de série, texto + status da OS, status + datas).",
    "Escreva em português simples. Sem jargão que o dono da base não usaria.",
  ]},
]},

{ t: "As fontes e o que cada campo significa", itens: [
  {p: "A base SS/OS tem 64 colunas. Leia todas. Abaixo, o que cada grupo diz e como usar."},
  {h3: "Base SS/OS — identificação e vínculo"},
  {tab: {w: [28, 72], h: ["Campo", "Como ler"], r: [
    ["NUMERO_SS", "Chave do caso. Se repetir, é a mesma SS com mais de uma OS ou mais de um registro de campo; junte tudo num caso só."],
    ["NUMERO_OS", "Ordem de serviço que atendeu a SS. Vazio = ninguém foi despachado (ou o vínculo não foi feito). É a chave para a base OS Status."],
    ["NUM_OBRA", "Obra vinculada. Vazio depois de 60 dias da abertura é sinal de falta de comprovação."],
    ["NUM_TRAFO", "Código operativo do transformador. É a chave do histórico: procure todas as SS deste código na base inteira. Guarde os zeros à esquerda. Se não achar, tente a chave gêmea “03” + os 8 últimos dígitos."],
    ["DESCICAO_DO_ATIVO", "Nome do ativo no cadastro. Se disser religador, regulador, poste, chave ou banco, a SS foi aberta no ativo errado."],
    ["ALIMENTADOR / LOCALIDADE / RURA_URBANO", "Contexto. Vários chamados no mesmo alimentador no mesmo dia sugerem tempestade (descarga atmosférica plausível)."],
    ["COD_EQUIPE / ORG_SOLIC / SOLICITANTE", "Quem atendeu e quem pediu. Solicitante que abre a mesma SS várias vezes gera duplicidade."],
  ]}},
  {h3: "Base SS/OS — classificação"},
  {tab: {w: [28, 72], h: ["Campo", "Como ler"], r: [
    ["ORIGEM_SS / DEFEITO_SS", "O que quem abriu o chamado suspeitava. Valores comuns: QUEIMADO, AVARIADO, FURTADO, SOBRECARGA PREVENTIVA, POSTE, GARANTIA DE TRAFO; defeitos: DESCARGA ATMOSFÉRICA, NÃO IDENTIFICADO, VAZAMENTO DE ÓLEO, BUCHA DANIFICADA, SOBRECARGA, ABALROADO, VANDALISMO."],
    ["ORIGEM / DEFEITO", "A mesma classificação, mas na OS (depois do atendimento). Quando divergir da SS, vale a OS e você registra a divergência."],
    ["ESQUEMA", "Esquema de serviço. “MC - SUBSTITUIÇÃO DE TRANSFORMADOR” é o padrão. “MC - REMANEJAMENTO DE TRANSFORMADOR” já entrega a categoria. Ferragens, condutor, para-raios, conexão: o transformador provavelmente não foi trocado."],
    ["TASK / TIPOSS", "AVISO DE ANOMALIA nasce da operação; SOLICITAÇÃO DE SERVIÇO nasce de alguém pedindo. Não muda a categoria, mas explica textos vazios ou genéricos."],
    ["CRITICIDADE_SS", "Emergencial deveria fechar em horas. Emergencial que leva dias é sinal de que não era emergência (preventivo, programado) ou de fechamento administrativo."],
    ["SITUACAO_SS", "Se ainda estiver aberta ou pendente, o caso não pode ser fechado. Categoria provisória, marcada PENDENTE."],
  ]}},
  {h3: "Base SS/OS — datas"},
  {tab: {w: [28, 72], h: ["Campo", "Como ler"], r: [
    ["DATA_ABERTURA_SS", "Momento da suspeita. Todo cálculo de janela parte daqui."],
    ["DATA_TERMINO_SS", "Momento em que a SS foi encerrada. Pode vir antes da abertura (erro) ou em lote (vários casos encerrados no mesmo minuto, tipo 01/02 12:00). Nesses casos não use para medir duração."],
    ["DATA_LIMITE_SS", "Prazo. Término depois do limite é atraso, informativo apenas."],
    ["ANO", "Confira contra a abertura. Divergência é erro de carga."],
  ]}},
  {h3: "Base SS/OS — textos"},
  {tab: {w: [28, 72], h: ["Campo", "Como ler"], r: [
    ["DESCRICAO_OS", "A conclusão da equipe. É o texto mais importante. Leia inteiro; o motivo real costuma estar no fim, depois do texto padrão de despacho."],
    ["DESCRIPTION_SS", "O que foi escrito ao abrir. Vale como suspeita inicial e para pegar palavras como furto, abalroamento, remanejamento, tape, divisão de circuito."],
    ["PROVÁVEL_MOTIVO_DO_DEFEITO", "Campo do formulário de campo. Dá a causa na visão de quem trocou: descarga, sobrecarga, bucha, vazamento, não identificado."],
  ]}},
  {h3: "Base SS/OS — formulário de campo (a prova física)"},
  {tab: {w: [28, 72], h: ["Campo", "Como ler"], r: [
    ["NS_RETIRADO / TOMBAMENTO_RETIRADO", "Número de série e patrimônio do transformador que saiu. Vazio, “0”, “00” ou “N/A” é o mesmo que vazio. Sem isso não há prova de que um transformador saiu do poste."],
    ["NS_INSTALADO / TOMBAMENTO_INSTALADO", "O que entrou. Retirado igual ao instalado = não houve troca. Instalado preenchido e retirado vazio = instalação nova, divisão de circuito ou registro incompleto."],
    ["FABRICANTE_* / DATA_FABRICACAO_*", "Idade do equipamento retirado. Mais de 25 anos apoia envelhecimento. Data de fabricação do instalado depois da abertura da SS é erro de digitação."],
    ["REFORMADORA_* / DATA_REFORMA_* / TRAFO_INSTALADO_É_REFORMADO / TRANSFORMADOR_RETIRADO_É_R…", "Se o retirado era reformado e a reforma é recente (menos de 24 meses), a falha é prematura: registre alerta de garantia. Combine com ORIGEM_SS = GARANTIA DE TRAFO."],
    ["POTENCIA_RET / POTENCIA_INST", "Instalado maior que retirado sugere sobrecarga ou melhoria de posto. Menor sugere divisão de circuito ou remanejamento. Igual é a troca comum por falha."],
    ["QTD_CLIENTES", "Zero ou vazio com texto falando em religador, regulador ou particular: transformador auxiliar, não conta."],
    ["ATERRAMENTO_ESTA_CONECTADO / MEDIÇÃO_DE_ATERRAMENTO_* / FEZ_MELHORIA_DE_ATERRAMENT…", "Aterramento ruim ou medido alto apoia descarga atmosférica como causa. Melhoria feita apoia que a equipe atribuiu a falha a isso."],
    ["PARA_RAIOS_INSTALADO_SUBST…", "Para-raios trocado junto reforça descarga atmosférica."],
    ["EXISTE_VEGETAÇÃO_TOCANDO_A…", "Sim apoia curto por vegetação (queimado, causa externa à rede mas falha do trafo)."],
    ["FEITO_COLA_E_FITA / QUAL_ELO_INSTALADO / TIPO_DE_BARRAMENTO / INSTALOU_ALGUM_ESPAÇADOR", "Detalhes de execução. Elo trocado sem NS de transformador aponta para SUBSTITUIÇÃO DE CHAVE FUSÍVEL."],
    ["EQUIPAMENTO_APRESENTA_VAZA…", "Sim com ORIGEM avariado confirma AVARIADO por vazamento."],
    ["NUM_INT", "Número da interrupção, quando preenchido. Não é a Crítica, mas indica que houve desligamento associado."],
  ]}},
  {h3: "Base OS Status"},
  {p: "Os nomes de coluna podem variar. Mapeie pelo significado e declare o mapeamento que usou no início do relatório."},
  {tab: {w: [30, 70], h: ["Informação esperada", "Para que serve"], r: [
    ["Número da OS", "Chave para casar com NUMERO_OS da base SS/OS."],
    ["Status / situação da OS", "Aberta, programada, em execução, executada, encerrada, cancelada, suspensa. Só executada ou encerrada comprovam atendimento."],
    ["Data de abertura, programação, início e fim de execução, encerramento", "Reconstroem a linha do tempo. Execução antes da abertura da SS = OS de outra ocorrência. Programada com dias de antecedência = serviço planejado."],
    ["Tipo de conclusão / motivo de cancelamento", "“Serviço não executado”, “equipamento normal”, “cancelada a pedido” encerram o caso como SEM TROCA."],
    ["Equipe / executante", "Confere com COD_EQUIPE. Divergência é alerta de vínculo."],
  ]}},
]},

{ t: "Preparação dos dados antes de ler qualquer caso", itens: [
  {n: [
    "Normalize textos: tire espaços das pontas, converta para maiúsculas e remova acentos apenas para comparar. Mantenha o texto original para citar.",
    "Converta datas para data e hora de verdade. Aceite “dd/mm/aaaa hh:mm:ss” e o formato ISO com “T”. Data que não converte vira alerta DATA_INVÁLIDA, nunca vira zero.",
    "Trate como vazio: célula em branco, “0”, “00”, “N/A”, “NA”, “SEM”, “-”, “NÃO INFORMADO”. Vale para NS, tombamento, obra e OS.",
    "Preserve NUM_TRAFO como texto com zeros à esquerda. Gere a chave gêmea “03” + últimos 8 dígitos e use só quando o código inteiro não aparecer em lugar nenhum.",
    "Agrupe por NUMERO_SS. Uma SS com várias linhas vira um caso com uma lista de OS e uma lista de registros de campo. Não conte a mesma SS duas vezes.",
    "Ligue SS → OS pelo NUMERO_OS, OS → OS Status pelo número da OS, e monte o índice do histórico: NUM_TRAFO → todas as SS da base, em ordem de abertura.",
    "Monte o índice de séries: NS_RETIRADO e NS_INSTALADO de todas as linhas, para rastrear onde um transformador esteve antes.",
    "Fixe a data de referência (“hoje”) uma vez e use a mesma em toda a rodada. Declare-a no relatório.",
  ]},
]},

{ t: "Histórico do transformador (obrigatório antes de categorizar)", itens: [
  {p: "Antes de olhar o texto da SS, levante o passado do transformador. A categoria de hoje muda de acordo com o que aconteceu antes."},
  {b: [
    "Liste todas as SS do mesmo NUM_TRAFO, com abertura, categoria (se já lida), ORIGEM, NS retirado e instalado.",
    "Conte SS nos últimos 30, 90 e 365 dias antes desta abertura. Duas ou mais em 90 dias = REINCIDENTE. Três ou mais em 365 = CRÔNICO.",
    "Confira a continuidade das séries: o NS_INSTALADO da SS anterior deveria ser o NS_RETIRADO desta. Se bater, o histórico fecha. Se não bater, houve troca sem SS ou erro de registro: alerta TROCA_SEM_SS.",
    "Procure o NS_RETIRADO desta SS como NS_INSTALADO em qualquer outra SS. Se o mesmo equipamento saiu e voltou, alerta PING_PONG (reformado voltando ou remanejamento disfarçado).",
    "Veja se a SS anterior era FURTO. Furto seguido de nova SS “queimado” em poucas semanas costuma ser a reposição do furtado, não uma queima.",
    "Veja se existe outra SS aberta e ainda pendente no mesmo transformador. Se existir, uma das duas é duplicada ou o serviço não foi feito.",
    "Olhe o alimentador no mesmo dia: cinco ou mais SS de queimado no mesmo alimentador em 24 horas sustentam descarga atmosférica como causa comum.",
    "Registre o resumo do histórico em uma linha: “3ª SS em 12 meses; anterior em 14/03 (queimado, NS 12345 instalado = NS retirado hoje); sem furto prévio”.",
  ]},
  {p: "Se o transformador for reincidente e a leitura de hoje apontar QUEIMADO por descarga, mantenha a categoria mas eleve o alerta: reincidência sugere aterramento ruim, sobrecarga crônica ou preventivo mal registrado. Isso vai para o campo de causa, não muda o “conta”."},
]},

{ t: "Verificações de data e consistência (rode todas, em cada SS)", itens: [
  {p: "Cada verificação tem um código. No relatório, cite os códigos disparados. Elas não decidem sozinhas a categoria; elas mudam a confiança e apontam onde olhar."},
  {tab: {w: [8, 40, 52], h: ["Cód.", "Verificação", "O que significa e o que fazer"], r: [
    ["D1", "DATA_TERMINO_SS anterior a DATA_ABERTURA_SS", "Data inválida. Não calcule duração. Se várias SS terminam no mesmo minuto (ex.: 01/02 12:00), é fechamento administrativo em lote: o término não diz nada sobre o atendimento. Use as datas da OS Status no lugar."],
    ["D2", "Duração = término − abertura, comparada com CRITICIDADE_SS", "Emergencial acima de 24 h: desconfie. Acima de 7 dias: provável serviço programado ou SS que ficou aberta por esquecimento. Combine com a data de execução da OS."],
    ["D3", "Término depois de DATA_LIMITE_SS", "Atraso. Só informativo; não muda categoria."],
    ["D4", "Hoje − abertura maior que 60 dias e NUM_OBRA vazio", "Passou o prazo de apropriação. Se a OS Status estiver executada/encerrada: SEM OBRA — PASSADOS 60 DIAS. Se estiver aberta/programada: PENDENTE. Se cancelada: SEM TROCA."],
    ["D5", "SITUACAO_SS aberta/pendente há mais de 30 dias", "Caso não fechado. Dê categoria provisória e marque PENDENTE. Não conte."],
    ["D6", "Execução ou encerramento da OS antes da abertura da SS", "A OS não é desta ocorrência: vínculo errado. Trate como se a SS não tivesse OS e registre alerta VÍNCULO_OS."],
    ["D7", "OS Status cancelada, suspensa ou “não executada”", "Ninguém trocou nada. Categoria SEM TROCA (se houve visita) ou SEM OS E SEM OBRA (se nunca houve OS válida)."],
    ["D8", "NS_RETIRADO igual a NS_INSTALADO", "Não houve substituição. SEM TROCA, salvo se o texto explicar remanejamento do mesmo equipamento."],
    ["D9", "NS_RETIRADO e NS_INSTALADO vazios, mas DESCRICAO_OS fala em troca", "Troca sem prova física. RETIDO — SEM PROVA DE TROCA. Não conta até aparecer o número de série."],
    ["D10", "NS_INSTALADO preenchido e NS_RETIRADO vazio", "Instalação sem retirada. Leia o texto: divisão de circuito, novo posto, ou registro incompleto. Sem texto, RETIDO."],
    ["D11", "DATA_FABRICACAO_INSTALADO depois da abertura", "Erro de digitação. Alerta, sem efeito na categoria."],
    ["D12", "POTENCIA_INST diferente de POTENCIA_RET", "Maior: verifique sobrecarga ou melhoria de posto. Menor: verifique divisão de circuito ou remanejamento. Igual: troca comum."],
    ["D13", "QTD_CLIENTES zero ou vazio", "Confira DESCICAO_DO_ATIVO e texto. Religador, regulador, particular ou auxiliar: AUXILIAR DE RELIGADOR ou ERRO DE CADASTRO."],
    ["D14", "ESQUEMA diferente de substituição de transformador", "Remanejamento: REMANEJAMENTO. Ferragens, condutor, conexão, para-raios: provável POSTE/REDE ou SUBSTITUIÇÃO DE CHAVE FUSÍVEL; confirme no texto e no NS."],
    ["D15", "ORIGEM_SS diferente de ORIGEM (OS)", "A OS manda. Registre a divergência no campo “contradições”."],
    ["D16", "DEFEITO_SS, DEFEITO e PROVÁVEL_MOTIVO_DO_DEFEITO não combinam", "Use para a causa provável, não para a categoria. Anote os três."],
    ["D17", "Outra SS no mesmo NUM_TRAFO com abertura a menos de 48 h", "Provável duplicidade. Mantenha a que tem OS executada e NS preenchido; a outra vira SS DUPLICADA."],
    ["D18", "DESCICAO_DO_ATIVO não é transformador", "ERRO DE CADASTRO — NÃO É TRANSFORMADOR, mesmo que o texto fale em trafo."],
    ["D19", "Retirado reformado com DATA_REFORMA_RET a menos de 24 meses", "Falha prematura. Alerta GARANTIA. Não muda o conta."],
    ["D20", "DATA_FABRICACAO_RETIRADO com mais de 25 anos", "Apoia envelhecimento como causa. Registre no campo de causa."],
  ]}},
]},

{ t: "Como ler os textos", itens: [
  {n: [
    "Leia primeiro DESCRICAO_OS por inteiro. Ignore o cabeçalho padrão de despacho (“medido_ emergencial_ substituição de trafo…”) e procure a frase escrita pela equipe, que costuma vir depois.",
    "Depois DESCRIPTION_SS. Depois PROVÁVEL_MOTIVO_DO_DEFEITO. Depois os demais campos do formulário.",
    "Verbo no passado é fato (“foi trocado”, “constatado queimado”). Verbo no futuro ou infinitivo é intenção (“substituir trafo”, “verificar”): não prova nada.",
    "Negação vale mais que afirmação: “NÃO estava queimado”, “não foi necessária a troca”, “equipamento normal” derrubam qualquer suspeita da SS.",
    "Texto genérico (“substituição de transformador”, “trafo queimado”) sem detalhe não decide sozinho. Nesse caso a decisão vem do NS, do status da OS e do histórico.",
    "Quando SS e OS se contradizem, vale a OS. Quando a OS está vazia, vale SS + formulário. Quando tudo é vazio ou genérico, marque INCONCLUSIVO ou RETIDO, nunca QUEIMADO por inércia.",
    "Cite sempre o trecho exato entre aspas e o campo de onde veio.",
  ]},
  {h3: "Palavras que puxam categoria (procure sem acento e em maiúsculas)"},
  {tab: {w: [30, 70], h: ["Categoria", "Palavras e expressões"], r: [
    ["FURTO", "FURT, ROUB, LEVARAM, SUBTRA, SUMIU O TRAFO, VANDAL (junto com sumiço)"],
    ["ABALROAMENTO", "ABALRO, COLIS, BATEU NO POSTE, VEICULO, CAMINHAO, CARRETA, ACIDENTE DE TRANSITO"],
    ["DANO DE TERCEIROS", "TERCEIRO, QUEIMADA, FOGO NA VEGETACAO, DISPARO, TIRO, OBRA DE TERCEIRO, VANDALISMO (sem sumiço)"],
    ["REMANEJAMENTO", "REMANEJ, TRANSFERI, MUDAN DE POSTE, DESLOC, RETIRADO PARA OUTRO PONTO"],
    ["PREVENTIVO/PROGRAMADO", "PREVENTIV, PROGRAMAD, INSPECAO, TERMOGRAF, CAMPANHA, VIDA UTIL, NAO ESTAVA QUEIMADO, EQUIPAMENTO NORMAL, GARANTIA"],
    ["TAPE/REGULARIZAÇÃO DE TENSÃO", "TAPE, TAP, TENSAO BAIXA, TENSAO ALTA, REGULARIZA TENSAO, NIVEL DE TENSAO, RECLAMACAO DE TENSAO"],
    ["DIVISÃO DE CIRCUITO", "DIVISAO DE CIRCUITO, DIVIDIR CARGA, NOVO CIRCUITO, NOVO POSTO, INSTALACAO DE TRAFO (sem retirada)"],
    ["MELHORIA DE POSTO", "MELHORIA, ADEQUACAO, REFORMA DO POSTO, AUMENTO DE POTENCIA, TROCA DE ESTRUTURA"],
    ["AUXILIAR DE RELIGADOR", "AUXILIAR, RELIGADOR, REGULADOR, ALIMENTA O RELIGADOR, TRAFO DE SERVICO"],
    ["POSTE/REDE", "POSTE QUEBRADO, POSTE CAIDO, CONDUTOR, CABO ROMPIDO, CONEXAO, FERRAGEM, ESTRUTURA"],
    ["SUBSTITUIÇÃO DE CHAVE FUSÍVEL", "CHAVE FUSIVEL, ELO, CARTUCHO, FUSIVEL QUEIMADO (sem troca de trafo)"],
    ["FALTA DE FASE", "FALTA DE FASE, FASE ABERTA, UMA FASE, CONEXAO SOLTA, JUMPER"],
    ["SEM TROCA", "NAO FOI TROCADO, NAO HOUVE SUBSTITUICAO, RELIGADO, NORMALIZADO SEM TROCA, EQUIPAMENTO OK, NAO CONSTATADO DEFEITO"],
    ["AVARIADO", "VAZAMENTO, VAZANDO OLEO, BUCHA QUEBRADA, BUCHA TRINCADA, CARCACA, RUIDO, AVARIAD, DETERIORAD"],
    ["QUEIMADO", "QUEIMAD, CURTO, EXPLODIU, ESTOUROU, DESCARGA, RAIO, SOBRECARGA (com troca comprovada)"],
  ]}},
  {p: "Uma palavra sozinha não fecha categoria. “Queimado” na SS com “não foi trocado” na OS é SEM TROCA. “Furtado” na SS com NS retirado preenchido e texto de queima na OS é QUEIMADO (a SS errou)."},
]},

{ t: "Investigação da causa", itens: [
  {p: "Para cada SS que contar (QUEIMADO ou AVARIADO), diga por que o transformador falhou, com que confiança e com base em quê. A causa não muda o “conta”, mas é o que permite agir."},
  {tab: {w: [24, 40, 36], h: ["Causa provável", "Sinais nos dados", "O que reforça / o que enfraquece"], r: [
    ["Descarga atmosférica", "DEFEITO ou PROVÁVEL_MOTIVO = DESCARGA; para-raios substituído; aterramento não conectado ou medido alto; várias SS no mesmo alimentador no mesmo dia", "Reforça: época chuvosa, reincidência no mesmo posto. Enfraquece: dia sem outros chamados na região, aterramento bom, para-raios intacto."],
    ["Sobrecarga", "DEFEITO = SOBRECARGA; POTENCIA_INST maior que POTENCIA_RET; QTD_CLIENTES alto para a potência; ORIGEM_SS = SOBRECARGA PREVENTIVA", "Reforça: histórico de tape ou reclamação de tensão no mesmo trafo. Enfraquece: potência mantida."],
    ["Envelhecimento", "DATA_FABRICACAO_RETIRADO com mais de 25 anos; PROVÁVEL_MOTIVO = NÃO IDENTIFICADO; sem descarga nem sobrecarga", "Reforça: fabricante antigo, sem reforma. Enfraquece: reformado há pouco tempo (aí é falha prematura)."],
    ["Falha prematura de reformado", "TRANSFORMADOR_RETIRADO_É_REFORMADO = sim; DATA_REFORMA_RET a menos de 24 meses; ORIGEM_SS = GARANTIA DE TRAFO", "Sempre gera alerta GARANTIA com nome da reformadora."],
    ["Vazamento / bucha", "DEFEITO = VAZAMENTO DE ÓLEO ou BUCHA DANIFICADA; EQUIPAMENTO_APRESENTA_VAZA = sim", "Categoria AVARIADO. Reforça: texto da OS descrevendo o dano."],
    ["Vegetação", "EXISTE_VEGETAÇÃO_TOCANDO = sim; texto com galho, árvore, vegetação", "Queimado por causa externa à rede, mas falha do trafo: conta."],
    ["Ação de terceiros / furto / abalroamento", "Palavras da tabela anterior; NS retirado vazio (o trafo sumiu) no furto", "Não conta. Se o NS retirado estiver preenchido num furto, desconfie: alguém registrou o número do que sumiu ou a SS errou a origem."],
    ["Não identificada", "PROVÁVEL_MOTIVO = NÃO IDENTIFICADO e nada mais aponta", "Diga “não identificada” com confiança baixa. Não invente."],
  ]}},
  {p: "Quando dois sinais apontarem causas diferentes, escreva as duas com a confiança de cada uma. Exemplo: “descarga (média: para-raios trocado) ou sobrecarga (baixa: potência subiu de 45 para 75 kVA)”."},
]},

{ t: "Árvore de decisão (siga nesta ordem, pare na primeira que fechar)", itens: [
  {n: [
    "O ativo é transformador? (DESCICAO_DO_ATIVO, D13, D18). Não → ERRO DE CADASTRO ou AUXILIAR DE RELIGADOR. Pare.",
    "A SS está fechada? (SITUACAO_SS, D5). Não → categoria provisória + PENDENTE. Não conta. Continue só para registrar a leitura.",
    "Existe OS válida? (NUMERO_OS preenchido, OS Status encontrada, D6 sem disparo). Não → SEM OS E SEM OBRA se hoje − abertura > 60 dias; senão PENDENTE.",
    "A OS foi executada? (OS Status executada/encerrada, D7). Não → SEM TROCA (cancelada após visita) ou SEM OS E SEM OBRA (cancelada sem visita).",
    "A OS nega a falha? (“não estava queimado”, “equipamento normal”, “não foi trocado”). Sim → SEM TROCA ou PREVENTIVO/PROGRAMADO, conforme o texto. Pare.",
    "A causa é externa? (FURTO, ABALROAMENTO, DANO DE TERCEIROS, POSTE/REDE, CHAVE FUSÍVEL, FALTA DE FASE — tabela de palavras + D14). Sim → a categoria correspondente. Pare.",
    "A troca foi planejada ou de rede? (PREVENTIVO, REMANEJAMENTO, TAPE, DIVISÃO DE CIRCUITO, MELHORIA DE POSTO — texto + ESQUEMA + D12). Sim → a categoria correspondente. Pare.",
    "É duplicada? (D17). Sim → SS DUPLICADA para a segunda. Pare.",
    "Há prova física da troca? (NS_RETIRADO preenchido e diferente de NS_INSTALADO, D8, D9, D10). Não → RETIDO — SEM PROVA DE TROCA. Pare.",
    "Há obra? (NUM_OBRA, D4). Não e passaram 60 dias → SEM OBRA — PASSADOS 60 DIAS. Pare.",
    "Qual foi a falha? Vazamento, bucha, carcaça, ruído → AVARIADO. Queima, curto, descarga, sobrecarga, explosão → QUEIMADO. Texto genérico com NS e obra em ordem → QUEIMADO com confiança média.",
    "Nada acima fechou → INCONCLUSIVO. Escreva o que falta para fechar.",
  ]},
  {q: "Interrupção na Crítica e material da obra não são verificáveis com estas fontes. Não use AUSENTE DA CRÍTICA, FORA DA JANELA, OBRA SEM TRANSFORMADOR NO MATERIAL nem OBRA SEM EXECUÇÃO. Onde essas verificações seriam necessárias, escreva NÃO VERIFICÁVEL COM ESTAS FONTES no campo de pendências."},
]},

{ t: "Fichas das categorias", itens: [
  {h3: "Contam no indicador"},
  {tab: {w: [18, 30, 26, 26], h: ["Categoria", "Definição e gatilhos", "Confirma", "Não use quando"], r: [
    ["QUEIMADO", "Falha interna do transformador com troca. ORIGEM = QUEIMADO; texto de queima/curto/descarga na OS; NS retirado ≠ instalado; OS executada.", "PROVÁVEL_MOTIVO preenchido; para-raios ou aterramento mexidos; obra vinculada; potência igual.", "OS nega a troca; NS vazio (RETIDO); texto só da SS sem OS; esquema não é substituição."],
    ["AVARIADO", "Dano físico sem queima, com troca. ORIGEM = AVARIADO; vazamento, bucha, carcaça, ruído; EQUIPAMENTO_APRESENTA_VAZA = sim.", "NS retirado ≠ instalado; OS executada; obra.", "O texto revela tape, tensão ou preventivo (avariado é a origem favorita para esconder programado)."],
  ]}},
  {h3: "Não contam — causa externa"},
  {tab: {w: [18, 30, 26, 26], h: ["Categoria", "Definição e gatilhos", "Confirma", "Não use quando"], r: [
    ["FURTO", "Equipamento subtraído. ORIGEM_SS/DEFEITO_SS = FURTADO ou texto de furto.", "NS retirado vazio (não havia o que anotar); boletim citado.", "OS descreve queima e tem NS retirado: a SS errou a origem."],
    ["ABALROAMENTO", "Veículo derrubou o poste/trafo. DEFEITO = ABALROADO ou texto.", "Poste trocado junto; texto com veículo.", "Texto fala em abalroamento antigo e a falha atual é outra."],
    ["DANO DE TERCEIROS", "Queimada, obra, disparo, vandalismo sem sumiço.", "Texto explícito na OS.", "Só a SS menciona e a OS diz queima comum."],
    ["POSTE/REDE", "Falha em poste, condutor, conexão, estrutura; trafo só retirado para o serviço.", "ESQUEMA de ferragens/condutor; NS retirado = instalado.", "NS diferente e texto de queima."],
    ["SUBSTITUIÇÃO DE CHAVE FUSÍVEL", "Serviço foi elo/chave.", "QUAL_ELO_INSTALADO preenchido e NS vazio ou igual.", "Também trocou o trafo (aí é QUEIMADO)."],
    ["FALTA DE FASE", "Problema de fase na rede.", "Texto na OS; NS igual.", "Texto na OS diz que a falta de fase queimou o trafo e trocou: QUEIMADO."],
    ["ERRO DE CADASTRO — NÃO É TRANSFORMADOR", "Ativo cadastrado não é trafo.", "DESCICAO_DO_ATIVO; QTD_CLIENTES zero.", "Cadastro errado mas a OS trocou um trafo de verdade com NS: leia como QUEIMADO e alerte o cadastro."],
  ]}},
  {h3: "Não contam — troca sem falha"},
  {tab: {w: [18, 30, 26, 26], h: ["Categoria", "Definição e gatilhos", "Confirma", "Não use quando"], r: [
    ["PREVENTIVO/PROGRAMADO", "Troca planejada com o equipamento funcionando.", "OS programada com dias de antecedência (OS Status); duração longa (D2); ORIGEM_SS = SOBRECARGA PREVENTIVA ou GARANTIA; texto “não estava queimado”.", "Texto da OS descreve queima real."],
    ["REMANEJAMENTO", "Mesmo trafo mudou de poste.", "ESQUEMA = remanejamento; NS retirado = instalado ou PING_PONG; texto.", "NS diferente e texto de falha."],
    ["TAPE/REGULARIZAÇÃO DE TENSÃO", "Serviço de tensão.", "Texto; potência mudou; histórico de reclamação de tensão.", "OS diz que trocou por queima."],
    ["DIVISÃO DE CIRCUITO", "Novo trafo para dividir carga.", "NS instalado sem retirado (D10); potência menor; texto.", "Há retirada com NS e falha descrita."],
    ["MELHORIA DE POSTO", "Reforma/adequação planejada.", "Potência maior; texto de melhoria; OS programada.", "Falha descrita na OS."],
    ["AUXILIAR DE RELIGADOR", "Trafo de serviço de equipamento de rede.", "QTD_CLIENTES zero; texto; DESCICAO_DO_ATIVO.", "Atende clientes."],
  ]}},
  {h3: "Não contam — não houve troca ou falta prova"},
  {tab: {w: [18, 30, 26, 26], h: ["Categoria", "Definição e gatilhos", "Confirma", "Não use quando"], r: [
    ["SEM TROCA (NÃO SUBSTITUÍDO)", "Equipe foi e não trocou.", "D8; OS “não executada”/“normal”; texto negando.", "NS diferente preenchido."],
    ["SS DUPLICADA", "Mesma ocorrência, mesmo trafo, mais de uma SS.", "D17; uma das OS cancelada por duplicidade.", "Aberturas com mais de 7 dias de distância e duas trocas com NS diferentes (é reincidência, não duplicidade)."],
    ["SEM OS E SEM OBRA", "Só a SS existe.", "NUMERO_OS vazio ou OS inexistente na OS Status; NUM_OBRA vazio; > 60 dias.", "Menos de 60 dias (PENDENTE)."],
    ["SEM OBRA — PASSADOS 60 DIAS", "OS executada, mas sem obra após 60 dias.", "D4; OS Status executada.", "Obra apareceu; OS ainda aberta."],
    ["RETIDO — SEM PROVA DE TROCA", "Tudo indica troca, falta NS.", "D9; texto de troca sem série.", "NS aparece em outra linha da mesma SS (junte antes)."],
    ["AVALIAR COM O MATHEUS", "Depende de informação externa à base.", "Você escreveu a pergunta exata que precisa ser respondida.", "Você só não leu direito."],
    ["INCONCLUSIVO", "Documentos se contradizem sem desempate.", "Você listou as contradições.", "Existe OS executada com NS e texto claro."],
    ["PENDENTE", "Caso aberto ou dentro do prazo de apropriação.", "D5; OS Status aberta/programada; < 60 dias sem obra.", "SS fechada e OS executada."],
  ]}},
]},

{ t: "Simulações que você deve rodar em cada SS", itens: [
  {p: "Simular é responder “e se?” com os próprios dados. Cada simulação gera uma linha no campo “simulações” do caso."},
  {tab: {w: [6, 34, 60], h: ["#", "Simulação", "Como fazer e o que anotar"], r: [
    ["S1", "E se eu só tivesse a SS?", "Dê a categoria só por ORIGEM_SS, DEFEITO_SS e DESCRIPTION_SS. Compare com a categoria final. Se diferirem, anote “SS diria X; OS mostra Y”. Isso mede o quanto a SS engana."],
    ["S2", "E se o NS retirado for rastreado?", "Procure o NS_RETIRADO como NS_INSTALADO em outra SS. Ache onde e quando ele entrou. Calcule quanto tempo durou. Menos de 12 meses: falha prematura ou remanejamento."],
    ["S3", "E se a data de término for ignorada?", "Reconstrua a linha do tempo só com a OS Status (abertura, programação, execução, encerramento). Se a história mudar (ex.: SS diz 2 h, OS diz 9 dias), a SS foi fechada em lote."],
    ["S4", "E se o histórico do trafo pesar?", "Com 2+ SS em 90 dias, pergunte: a troca de hoje foi porque a anterior não resolveu? A causa anterior era a mesma? Anote a hipótese: sobrecarga crônica, aterramento, preventivo mal registrado."],
    ["S5", "E se a OS Status disser cancelada?", "Recalcule a categoria sem a OS. Se a resposta for diferente da atual, o caso é frágil: baixe a confiança."],
    ["S6", "E se aplicar a regra dos 60 dias em 30 e em 90?", "Recalcule o conta/não conta do lote com 30, 60 e 90 dias. Informe quantos casos mudam. Isso mostra a sensibilidade da regra."],
    ["S7", "E se os RETIDOS voltassem?", "Some os RETIDO ao total que conta. Informe os dois números: “conta hoje” e “conta se os retidos forem confirmados”."],
    ["S8", "E se o alimentador inteiro for olhado no dia?", "Conte SS de queimado no mesmo alimentador ±24 h. Cinco ou mais: registre “evento coletivo, descarga plausível” em todas."],
  ]}},
]},

{ t: "Saída obrigatória por SS", itens: [
  {p: "Entregue uma linha por SS com todos os campos abaixo, na ordem. Campo sem informação recebe “—”, nunca fica vazio."},
  {tab: {w: [26, 74], h: ["Campo de saída", "Conteúdo"], r: [
    ["NUMERO_SS / NUM_TRAFO / NUMERO_OS", "Chaves do caso."],
    ["Categoria", "Uma das fichas. Nada fora da lista."],
    ["Conta no indicador", "SIM ou NÃO. RETIDO, PENDENTE, INCONCLUSIVO e AVALIAR são NÃO."],
    ["Confiança", "ALTA (dois ou mais sinais fortes combinando), MÉDIA (texto genérico com NS e status em ordem), BAIXA (um sinal só ou contradição)."],
    ["Motivo", "Uma frase. Ex.: “OS diz que o equipamento não estava queimado; troca preventiva”."],
    ["Evidência", "Campo + trecho entre aspas. Ex.: DESCRICAO_OS: “NÃO FOI REALIZADA A TROCA, EQUIPAMENTO NÃO ESTAVA QUEIMADO”."],
    ["Contradições", "SS vs OS, campo vs texto. Ex.: “ORIGEM_SS = QUEIMADO; ORIGEM (OS) = AVARIADO”."],
    ["Verificações disparadas", "Códigos D1…D20 que acenderam."],
    ["Histórico do trafo", "Uma linha: nº de SS em 30/90/365 dias, última SS, continuidade de NS, furto prévio."],
    ["Causa provável", "Uma das causas da tabela + confiança + evidência."],
    ["Simulações", "Resultado de S1 a S8 quando aplicável."],
    ["Alertas", "GARANTIA, TROCA_SEM_SS, PING_PONG, VÍNCULO_OS, DATA_INVÁLIDA, EVENTO_COLETIVO, CADASTRO."],
    ["Pendências", "O que falta para fechar, incluindo NÃO VERIFICÁVEL COM ESTAS FONTES (interrupção, material)."],
    ["Categoria só pela SS (S1)", "Para medir quanto a SS engana."],
  ]}},
  {h3: "Resumo do lote"},
  {b: [
    "Total de SS, quantas contam, quantas não contam, quantas pendentes/retidas.",
    "Tabela por categoria com quantidade e porcentagem.",
    "Tabela de causa provável entre as que contam.",
    "Quantos casos mudam com 30/60/90 dias (S6) e quantos voltam se os retidos forem confirmados (S7).",
    "Lista dos alertas de dados: datas inválidas, fechamentos em lote, vínculos de OS errados, cadastros errados, garantias.",
    "Lista dos transformadores reincidentes e crônicos.",
    "Data de referência usada e mapeamento de colunas da OS Status.",
  ]},
]},

{ t: "Regras de ouro", itens: [
  {b: [
    "A conclusão da OS vale mais que a abertura da SS. Sempre.",
    "Sem número de série retirado não há troca comprovada. Retido, não queimado.",
    "Falta de prova é falta de prova. Não é prova de que o trafo estava bom.",
    "Retido não é excluído: pode voltar. Trate os retidos como a primeira fila de trabalho.",
    "Data em lote não mede nada. Use a OS Status para a linha do tempo.",
    "Uma ocorrência, um equipamento, uma SS. O resto é duplicado.",
    "Histórico primeiro, texto depois, categoria por último.",
    "O que estas bases não mostram, você não afirma. Escreva NÃO VERIFICÁVEL e siga.",
    "O indicador de 1.305 não muda. Você explica, não recalcula.",
  ]},
]},
]};
