# -*- coding: utf-8 -*-
NOVAS = {
"ETO-RD-AR 01352/2026": ("AVARIADO","SIM","Vazamento de óleo com troca comprovada: série 139287 saiu, 441005 entrou.","DESCRIPTION_SS: “Trafo com Vazamento de oleo” + OS com as duas séries","Média — o formulário aponta sobrecarga e a potência subiu de 75 para 112,5 kVA."),
"ETO-RD-AR 01353/2026": ("AVARIADO","SIM","Vazamento de óleo com troca comprovada: série 330080 saiu, 198865 entrou.","DESCRIPTION_SS: “Trafo com vazamento de oleo” + OS com as duas séries","Média — potência subiu de 75 para 112,5 kVA."),
"DOLP-RD-PA 00926/2026": ("PENDENTE — SS EM ABERTO","NÃO","SS ainda pendente, sem obra e sem série. Nada a decidir enquanto não fechar.","SITUACAO_SS = SS PENDENTE; NS retirado “00”","Alta"),
"ENC-RD-PS 00749/2026": ("RETIDO — SEM PROVA DE TROCA","NÃO","SS atendida, mas a OS só repete o texto da SS e não há série retirada nem instalada.","DESCRICAO_OS idêntica à SS; NS retirado “00000”, instalado “0”","Alta"),
"DOLP-RD-PA 00929/2026": ("RETIDO — SEM PROVA DE TROCA","NÃO","OS encerrada só com “baixado para consumo de material”, sem série. Término (18:00) anterior à abertura (21:42).","NS retirado “00”; DATA_TERMINO_SS < DATA_ABERTURA_SS","Alta"),
"ENC-RD-PS 00750/2026": ("AVARIADO","SIM","Vazamento de óleo com troca comprovada: 345384 saiu, 457562 entrou.","PROVÁVEL_MOTIVO_DO_DEFEITO = VAZAMENTO DE OLEO; OS com as duas séries","Média — aberta como queimado, mas o defeito registrado é vazamento."),
"ETO-RD-GU 00863/2026": ("QUEIMADO","SIM","Trafo constatado queimado penalizando 39 clientes; troca comprovada 26968 → 458829.","DESCRIPTION_SS: “FOI CONSTATADO TRAFO 5726292003 45KVA 13,8KV QUEIMADO, PENALIZANDO 39 CLIENTES”","Média — o formulário aponta vazamento e o texto da OS cita outra localidade (RDR de Araguaçu)."),
"ETO-RD-AR 01360/2026": ("QUEIMADO","SIM","SS e OS descrevem trafo queimado; troca comprovada 395694 → 337415, mesma potência.","DESCRIPTION_SS: “Trafo 5700009157 queimado 45kva”","Média — a OS foi classificada como sobrecarga preventiva, o que não bate com potência mantida."),
"DOLP-RD-PA 00933/2026": ("RETIDO — SEM PROVA DE TROCA","NÃO","“Trafo queimado” sem nenhuma série e sem obra; a OS só registra baixa de material.","NS retirado “0”, instalado “0”; NUM_OBRA vazio","Alta"),
"DOLP-RD-PA 00936/2026": ("RETIDO — SEM PROVA DE TROCA","NÃO","Trafo e para-raios queimados, mas sem série retirada ou instalada e sem obra.","NS retirado “00”; DESCRICAO_OS só repete a SS","Alta"),
"DOLP-RD-PA 00937/2026": ("RETIDO — SEM PROVA DE TROCA","NÃO","Trafo queimado com pedido de troca por 112,5 kVA, sem série e sem obra.","NS retirado “00”; NUM_OBRA vazio","Alta"),
"ENC-RD-PS 00756/2026": ("QUEIMADO","SIM","Troca comprovada 38366 → 606244 com descarga atmosférica no formulário.","PROVÁVEL_MOTIVO_DO_DEFEITO = DESCARGA ATMOSFERICA","Baixa — a OS veio vazia e o texto da SS fala em “avaliar possibilidade de levar trafo de 150 kVA”, com potência subindo de 112,5 para 150."),
"ETO-RD-AG 00942/2026": ("QUEIMADO","SIM","Trafo queimado com 49 clientes penalizados; troca comprovada 31083 → 611409, mesma potência.","DESCRIPTION_SS: “TRAFO QUEIMADO 5700658045 DE 75KVA … 49 CLIENTES PENALIZADOS”","Alta"),
"DOLP-RD-PA 00943/2026": ("PENDENTE — SS EM ABERTO","NÃO","Bucha primária danificada, SS ainda pendente, sem série e sem obra.","SITUACAO_SS = SS PENDENTE","Alta"),
"ETO-RD-GU 00869/2026": ("PENDENTE — SS EM ABERTO","NÃO","Trafo queimado, SS ainda pendente, sem série e sem obra.","SITUACAO_SS = SS PENDENTE","Alta"),
"ETO-RD-AG 00948/2026": ("QUEIMADO","SIM","Trafo e para-raios queimados; troca comprovada 543019 → 599394, mesma potência.","DESCRIPTION_SS: “Trafo 5748205127 queimado … Para raio: queimado”","Alta"),
"DOLP-RD-PA 00945/2026": ("PENDENTE — SS EM ABERTO","NÃO","Trafo queimado, SS ainda pendente, sem série e sem obra.","SITUACAO_SS = SS PENDENTE","Alta"),
"ETO-RD-AG 00950/2026": ("QUEIMADO","SIM","Queima por descarga atmosférica com para-raios queimado; troca 535581 → 832546.","PROVÁVEL_MOTIVO_DO_DEFEITO = DESCARGA ATMOSFERICA","Alta"),
"ETO-RD-AG 00957/2026": ("QUEIMADO","SIM","SS e OS dizem trafo queimado com para-raios queimado; troca 390972 → 554658.","DESCRIPTION_SS: “substituiçao de trafo 5701283103 queimado … para raio queimado”","Média — o formulário registrou vazamento de óleo e a potência subiu de 10 para 15 kVA."),
"DOLP-RD-PA 00953/2026": ("MELHORIA DE POSTO","NÃO","A troca é por carga, não por falha: pedido de trocar 15 kVA por 25 kVA porque o trafo não suporta os 48 clientes.","DESCRIPTION_SS: “trafo não esta suportando a carga do trafo”","Alta — o texto nega a queima com que a SS foi aberta."),
"ETO-RD-GU 00878/2026": ("PENDENTE — SS EM ABERTO","NÃO","Trafo queimado, SS ainda pendente, sem série e sem obra.","SITUACAO_SS = SS PENDENTE","Alta"),
"ETO-RD-GU 00880/2026": ("PENDENTE — SS EM ABERTO","NÃO","Trafo queimado com para-raios queimado, SS ainda pendente, sem série e sem obra.","SITUACAO_SS = SS PENDENTE","Alta"),
"DOLP-RD-PA 00955/2026": ("PENDENTE — SS EM ABERTO","NÃO","Trafo queimado com 1 cliente penalizado, SS ainda pendente, sem série e sem obra.","SITUACAO_SS = SS PENDENTE","Alta"),
}
