# -*- coding: utf-8 -*-
import json
b1 = [
{"ss":"DOLP-RD-PA 00713/2026","trafo":"5364882001","classificacao":"AVARIADO","conta_no_indicador":True,"confianca":"média",
 "justificativa":"Trafo energizando a estrutura (dando choque); a manutenção foi ao local, refez a malha de aterramento e ainda assim condenou o transformador. Condenação do próprio equipamento com substituição efetivada (série 374862 retirada / 203008 instalada, mesma potência 15 kVA), o que caracteriza avaria e não remanejamento. Julho não foi carregado na base de interrupção, então não houve conferência na Crítica.",
 "evidencia":"Manutenção foi ao local recuperar malha de aterramento e condenou o TRAFO.","prova_de_troca":"série"},
{"ss":"DG-RD-PO 00449/2026","trafo":"5700396250","classificacao":"FURTO","conta_no_indicador":False,"confianca":"alta",
 "justificativa":"SS, OS e formulário de campo convergem: transformador furtado na RDR de Ipueiras, inclusive o para-raio. Não há falha do equipamento. Sem conferência na base de interrupção (julho não carregado).",
 "evidencia":"instalar trafo 5700396250 FURTADO na RDR de impueiras","prova_de_troca":"série"},
{"ss":"ETO-RD-AG 00702/2026","trafo":"5710461039","classificacao":"QUEIMADO","conta_no_indicador":True,"confianca":"alta",
 "justificativa":"SS e OS descrevem trafo queimado; a OS traz os dados do retirado (TRAEL 2005, série 53662, CITD 680615) e do instalado (ITAM 2026, série C.299686, CITD 150637), mesma potência 15 kVA. Troca por falha do equipamento. Sem conferência na base de interrupção (julho não carregado).",
 "evidencia":"deslocar equipe da manutenção no trafo 5710461039 queimado 13,8 kv","prova_de_troca":"série"},
{"ss":"ETO-RD-AR 01095/2026","trafo":"5710025025","classificacao":"TAPE/REGULARIZAÇÃO DE TENSÃO","conta_no_indicador":False,"confianca":"baixa",
 "justificativa":"O único relato de condição é TAP submerso com tensão baixa em campo — comutador interno inacessível para ajuste, resolvido com troca por outro de mesma potência (25 kVA) e mesma tensão. Não há descrição de queima, vazamento, bucha quebrada ou falta de fase; o campo aponta motivo SOBRECARGA. Fica como regularização de tensão, não avaria. O texto não fecha e julho não foi carregado, portanto sem conferência na base de interrupção.",
 "evidencia":"Substitui trafo 5710025025 TAP submerso e a tensão esta baixa em campo.","prova_de_troca":"série"},
{"ss":"ETO-RD-GR 00720/2026","trafo":"5720015066","classificacao":"DIVISÃO DE CIRCUITO","conta_no_indicador":False,"confianca":"alta",
 "justificativa":"Instalação de posto de transformação novo em divisão de circuito: não houve equipamento retirado (NS e tombamento retirado = 0), apenas trafo de 25 kVA instalado. Não há falha de equipamento.",
 "evidencia":"INSTALAÇÃO DE POSTO DE TRANSFORMAÇÃO EM NOVA DIVISÃO DE CIRCUITO","prova_de_troca":"nenhuma"},
{"ss":"ETO-RD-AG 00717/2026","trafo":"5700573039","classificacao":"AVARIADO","conta_no_indicador":True,"confianca":"média",
 "justificativa":"A SS descreve avaria física do equipamento — carcaça energizada dando choque — e o formulário de campo aponta motivo do defeito DESCARGA ATMOSFERICA. A OS traz apenas o plano de medida de sobrecarga (10 para 25 kVA), título que não anula a descrição de avaria no corpo. Houve aumento de potência aproveitado na mesma intervenção, por isso confiança média. Julho não carregado: sem conferência na base de interrupção.",
 "evidencia":"Substituição do Trafo-5700573039 -10 Kva - 19,9 Kv - Avariado , defeito na carcaça dando choque energisada","prova_de_troca":"série"},
{"ss":"ETO-RD-AR 01109/2026","trafo":"5700968080","classificacao":"QUEIMADO","conta_no_indicador":True,"confianca":"alta",
 "justificativa":"SS relata trafo queimado e com vazamento de óleo; o formulário confirma vazamento (Sim) e motivo descarga atmosférica; a OS traz retirado (ITB 2011, série 767732) e instalado (ITAM 2026, série C 303356). Falha do equipamento com troca comprovada. Sem conferência na base de interrupção (julho não carregado).",
 "evidencia":"substituir trafo 5700968080 queimado e com vazamento de oleo","prova_de_troca":"série"},
{"ss":"ETO-RD-AG 00729/2026","trafo":"5712592130","classificacao":"REMANEJAMENTO","conta_no_indicador":False,"confianca":"baixa",
 "justificativa":"A SS é de cabo de BT deteriorado (400 m de TP 35) e menciona de passagem vazamento de óleo no trafo, mas a OS está vazia e o formulário do executante nega vazamento (Não), aponta motivo SOBRECARGA, com potência subindo de 75 para 112,5 kVA e trafo instalado reformado. A única leitura sustentada pelo que o executante registrou é troca por potência. A contradição entre SS e campo mantém a confiança baixa; julho não carregado, sem conferência na base de interrupção.",
 "evidencia":"EQUIPAMENTO_APRESENTA_VAZAMENTO_DE_OLEO: Não / PROVÁVEL_MOTIVO_DO_DEFEITO: SOBRECARGA (pot_ret 75 -> pot_inst 112.5)","prova_de_troca":"série"},
{"ss":"ETO-RD-GU 00734/2026","trafo":"5719414148","classificacao":"FURTO","conta_no_indicador":False,"confianca":"alta",
 "justificativa":"SS, OS e campo indicam furto do transformador de 30 kVA na RDR de São Valério, com substituição por outro de mesma potência. Não há falha do equipamento. Sem conferência na base de interrupção (julho não carregado).",
 "evidencia":"Segue SS de trafo 5719414148 furtado para devidas tratativas com equipe de manutenção.","prova_de_troca":"série"},
{"ss":"ETO-RD-AR 01136/2026","trafo":"5700692040","classificacao":"FURTO","conta_no_indicador":False,"confianca":"alta",
 "justificativa":"Origem, defeito e formulário de campo registram FURTADO; não há equipamento retirado (NS e tombamento retirado = 0), apenas instalação de trafo de 15 kVA. Não há falha de equipamento. Sem conferência na base de interrupção (julho não carregado).",
 "evidencia":"PROVÁVEL_MOTIVO_DO_DEFEITO: FURTADO / NS_RETIRADO: 0","prova_de_troca":"texto"},
{"ss":"ETO-RD-GU 00775/2026","trafo":"5700194003","classificacao":"QUEIMADO","conta_no_indicador":True,"confianca":"alta",
 "justificativa":"Transformador de 75 kVA da RDU Gurupi queimado, com substituição executada e registrada (retirado série 9477183, WTW de 1994; instalado série 1667710, CITD 150690) e 69 clientes atendidos. Julho não carregado, então não houve conferência na base de interrupção.",
 "evidencia":"Transformador 5700194003 queimado , 75KVA - 13.8 , RDU GURUPI JD ELDORADO","prova_de_troca":"série"},
{"ss":"DOLP-RD-PA 00791/2026","trafo":"5707542122","classificacao":"SEM TROCA","conta_no_indicador":False,"confianca":"alta",
 "justificativa":"A SS pediu substituição por queima, mas o executante fechou a OS como serviço não executado, o trafo ficou em serviço e o formulário não traz série nem tombamento (00). A Crítica casou pelo trafo e a observação confirma: a equipe fez melhorias e não precisou substituir o transformador.",
 "evidencia":"SERVIÇO NÃO EXECUTADO POIS O MESMO ESTAVA NORMAL EM COMPRA","prova_de_troca":"nenhuma"},
{"ss":"DG-RD-PO 00489/2026","trafo":"5700689043","classificacao":"FURTO","conta_no_indicador":False,"confianca":"alta",
 "justificativa":"Furto confirmado em três fontes: SS, formulário de campo (FURTADO) e Crítica, que casou pelo trafo com causa CAUSADA POR TERCEIROS / ROUBO DE TRANSFORMADOR.",
 "evidencia":"TR 5700689043 encontrado com a HC aberta, e ao verificar foi constatado que o mesmo está sem núcleo (Furtado).","prova_de_troca":"série"},
{"ss":"ETO-RD-GU 00790/2026","trafo":"5710471003","classificacao":"FURTO","conta_no_indicador":False,"confianca":"alta",
 "justificativa":"Trafo furtado em campo, com fotos enviadas ao supervisor; a OS confirma a substituição por outro de 15 kVA e o campo registra motivo FURTADO. O código não aparece na base de interrupção (ausente da Crítica), o que é falta de registro e não evidência contrária.",
 "evidencia":"Segue nota para substuiçao de Trafo 5710471003 o mesmo furtado em campo","prova_de_troca":"série"}
]
json.dump(b1, open('saida_novos_2.json','w'), ensure_ascii=False, indent=1)
print(len(b1))
