# -*- coding: utf-8 -*-
REGRAS = [
    ("CONTAM NO INDICADOR — O TRANSFORMADOR FALHOU", None),
    ("QUEIMADO",
     "O transformador queimou por falha própria e foi trocado. É o caso padrão: a OS confirma a troca, a Crítica mostra a interrupção no período e a obra tem transformador no material. Conta."),
    ("AVARIADO",
     "O transformador não queimou, mas ficou danificado (vazamento de óleo, bucha quebrada, carcaça amassada, ruído anormal) e precisou ser trocado. Conta igual ao queimado."),

    ("NÃO CONTAM — A CAUSA NÃO FOI DO TRANSFORMADOR", None),
    ("FURTO",
     "O transformador foi furtado ou roubado. Não houve falha do equipamento, houve crime. Não conta."),
    ("ABALROAMENTO",
     "Veículo bateu no poste e derrubou ou danificou o transformador. A causa é externa. Não conta."),
    ("DANO DE TERCEIROS",
     "Terceiros danificaram o equipamento (obra, queimada, vandalismo, disparo). Mesma lógica do abalroamento. Não conta."),
    ("POSTE/REDE",
     "O que falhou foi o poste, o condutor, a conexão ou a estrutura. O transformador só foi retirado para permitir o serviço. Não conta."),
    ("SUBSTITUIÇÃO DE CHAVE FUSÍVEL",
     "O serviço foi trocar chave fusível ou elo. O transformador continua o mesmo. Não conta."),
    ("FALTA DE FASE",
     "O problema era falta de fase na rede (chave aberta, fusível queimado, conexão solta) e não o transformador. Não conta."),
    ("ERRO DE CADASTRO — NÃO É TRANSFORMADOR",
     "A SS foi aberta em cima de um ativo que não é transformador (religador, regulador, poste, chave). Erro de cadastro na abertura. Não conta."),

    ("NÃO CONTAM — HOUVE TROCA, MAS NÃO POR FALHA", None),
    ("PREVENTIVO/PROGRAMADO",
     "A troca foi planejada, com o equipamento ainda funcionando (inspeção, campanha, fim de vida útil, termografia). Se a própria OS diz que o equipamento não estava queimado, é preventivo. Não conta."),
    ("REMANEJAMENTO",
     "O mesmo transformador foi mudado de lugar (outro poste, outro ponto do circuito). Não houve falha nem substituição por defeito. Não conta."),
    ("TAPE/REGULARIZAÇÃO DE TENSÃO",
     "A troca foi para corrigir nível de tensão (mudança de tape ou troca por outro de tensão adequada). É ajuste de tensão, não falha. Não conta."),
    ("DIVISÃO DE CIRCUITO",
     "O transformador foi trocado ou instalado para dividir carga e criar novo circuito. É obra de rede. Não conta."),
    ("MELHORIA DE POSTO",
     "Reforma do posto de transformação (aumento de potência, troca de estrutura, adequação). Melhoria planejada. Não conta."),
    ("AUXILIAR DE RELIGADOR",
     "Transformador auxiliar que alimenta religador ou equipamento de rede, não clientes. Não entra no indicador de transformador de distribuição. Não conta."),

    ("NÃO CONTAM — NÃO HOUVE TROCA", None),
    ("SEM TROCA (NÃO SUBSTITUÍDO)",
     "A equipe foi ao local e o transformador não foi trocado: era outro defeito, foi só religado, ou não havia problema. Sem troca não há baixa de equipamento. Não conta."),
    ("SS DUPLICADA",
     "Duas ou mais SS para a mesma ocorrência e o mesmo transformador. Só a primeira vale; as demais contariam o mesmo equipamento duas vezes. Não conta."),

    ("NÃO CONTAM — FALTA REGISTRO OU DOCUMENTO", None),
    ("SEM OBRA — PASSADOS 60 DIAS",
     "Existe SS e OS, mas nenhuma obra vinculada, e já se passaram mais de 60 dias da abertura. Depois desse prazo a ausência de obra deixa de ser atraso de apropriação e vira falta de comprovação. Não conta."),
    ("SEM OS E SEM OBRA",
     "Só existe a SS: não há ordem de serviço nem obra. Não há nada que comprove atendimento nem troca. Não conta."),
    ("OBRA SEM TRANSFORMADOR NO MATERIAL",
     "Existe obra, mas na lista de material não há transformador, só ferragem, condutor ou conexão. Se não saiu transformador do almoxarifado, não houve substituição. Não conta."),
    ("OBRA SEM EXECUÇÃO",
     "A obra existe no sistema mas nunca foi executada nem encerrada (sem apropriação, sem data de execução). Não conta."),
    ("AUSENTE DA CRÍTICA",
     "O transformador não aparece em nenhuma ocorrência da Crítica no período. Sem interrupção registrada não há evidência da falha. Não conta."),
    ("FORA DA JANELA DA CRÍTICA",
     "O transformador aparece na Crítica, mas a interrupção está fora da janela da SS (a regra aceita de 1 hora antes da abertura até 24 horas depois do fechamento). Fora disso é outra ocorrência. Não conta."),

    ("AINDA PENDENTES — PRECISAM DE UMA CONFERÊNCIA", None),
    ("RETIDO — SEM PROVA DE TROCA",
     "Tudo indica queima, mas falta a prova objetiva: não há número de série retirado ou instalado, nem material de transformador. Fica retido até alguém confirmar. Hoje não conta."),
    ("RETIDO — SEM INTERRUPÇÃO NA JANELA",
     "A troca está comprovada, mas não há interrupção correspondente na janela da Crítica. Retido até esclarecer se a Crítica ficou sem registro. Hoje não conta."),
    ("RETIDO — RESSALVA DA INTERRUPÇÃO",
     "Há interrupção na janela, mas a Crítica aponta outra causa (poste, condutor, terceiros) ou o transformador aparece só como elemento fechado. Retido. Hoje não conta."),
    ("AVALIAR COM O MATHEUS",
     "Caso que depende de informação que só o responsável da área tem (histórico do posto, decisão de campo). Segue em aberto."),
    ("INCONCLUSIVO",
     "Os documentos se contradizem ou o texto é genérico demais para decidir. Não se afirma nem queima nem expurgo. Hoje não conta."),
]

COMO_LER = [
    ("1. Ordem de leitura",
     "Primeiro a conclusão da OS (o que a equipe escreveu ao encerrar). Depois o texto da SS. Depois o formulário de campo. Depois a Crítica (interrupção). Por último o material da obra. O documento mais específico manda."),
    ("2. A palavra de quem executou vale mais",
     "Se a OS diz “não estava queimado”, “foi remanejado” ou “foi furtado”, vale isso — mesmo que a SS tenha sido aberta como queimado."),
    ("3. Janela da Crítica",
     "A SS casa com a ocorrência quando a abertura da SS cai entre 1 hora antes do início e 24 horas depois do fim da ocorrência."),
    ("4. Falta de registro não é prova de que não falhou",
     "Ausente da Crítica, sem obra e sem material são expurgos por falta de comprovação, não por certeza de que o transformador estava bom. Se o documento aparecer, o caso volta."),
    ("5. Retido não é excluído",
     "Retido significa “não conta hoje, mas pode voltar”. São os casos a resolver primeiro, porque são os que mais mudam o número."),
    ("6. Regra dos 60 dias",
     "Até 60 dias sem obra ainda é atraso normal de apropriação. Passados 60 dias, vira expurgo."),
    ("7. Uma ocorrência, um equipamento",
     "SS duplicada na mesma ocorrência e no mesmo transformador conta uma vez só."),
    ("8. O indicador de 1.305 não muda",
     "Esta leitura corre ao lado do caso. Nada aqui recalcula o indicador de 1.305 nem os universos de 1.582 e 1.510."),
]
